export const COLOR = {
  red: '#F54748',
  white: '#ffffff',
  whiteLight: '#FAFAFA',
  lightGray: '#F7F7F7',
  gray: 'rgb(200,202,205)',
  grayDark: '#DADBDD',
  black: 'rgb(46,46,46)',
  lightYellow: 'rgb(253,238,208)',
  darkYellow: '#e4b056',
  yellow: '#FDC55E',
  lightYellow: '#FFEAC4',
};

export const SIZES = {
  h1: {
    fontSize: 30,
    fontWeight: 'bold',
    color: COLOR.white,
    fontFamily: 'Poppins-SemiBold',
  },
  h2: {
    fontSize: 25,
    fontWeight: 'bold',
    color: COLOR.white,
    marginTop: 20,
    fontFamily: 'Poppins-Regular',
  },
  h3: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLOR.white,
    fontFamily: 'Poppins-Regular',
  },
  h4: {
    fontSize: 15,
    fontWeight: 'bold',
    color: COLOR.white,
    marginTop: 10,
    fontFamily: 'Poppins-Regular',
  },
  h5: {
    fontSize: 13,
    fontWeight: 'bold',
    color: COLOR.white,
    marginTop: 10,
    maxWidth: '70%',
    textAlign: 'center',
    lineHeight: 23,
    fontFamily: 'Poppins-Regular',
  },
  h6: {
    fontSize: 10,
    fontWeight: 'bold',
    color: COLOR.white,
    marginTop: 10,
    fontFamily: 'Poppins-Regular',
  },
  h7: {
    fontSize: 15,
    fontWeight: 'bold',
    fontFamily: 'Poppins-Regular',
    color: COLOR.white,
  },
  h8: {
    fontSize: 15,
    fontWeight: 'bold',
    color: COLOR.red,
    fontFamily: 'Poppins-Regular',
  },
  p: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLOR.black,
    fontFamily: 'Poppins-Regular',
  },
  title: {
    fontSize: 35,
    maxWidth: '60%',
    fontWeight: 'bold',
    color: COLOR.black,
    textAlign: 'center',
    fontFamily: 'Poppins-SemiBold',
    marginRight: 15,
  },
  subtitle: {
    fontSize: 16,
    color: COLOR.black,
    marginTop: 10,
    maxWidth: '80%',
    textAlign: 'center',
    lineHeight: 23,
    fontFamily: 'Poppins-Regular',
  },
  parraghy: {
    color: COLOR.red,
    fontSize: 35,
    fontWeight: 'bold',
  },
};
